<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class ActionsTableSeeder extends Seeder {
    public function run () {
        DB::table('actions')->insert(array(
           array('id'=>1, 
               'description'=>'Add users','code'=>'users_create'),
           array('id'=>2, 
               'description'=>'Edit users','code'=>'users_edit'),
           array('id'=>3, 
               'description'=>'Delete users','code'=>'users_destroy'),  
           array('id'=>4, 
               'description'=>'Update users','code'=>'users_update'),
           array('id'=>5, 
               'description'=>'Save created user','code'=>'users_store'),
           array('id'=>6, 
               'description'=>'List users','code'=>'users_index'),  
           array('id'=>7, 
               'description'=>'Add role','code'=>'roles_create'),
           array('id'=>8, 
               'description'=>'Add role','code'=>'roles_store'),
           array('id'=>9, 
               'description'=>'Edit role','code'=>'roles_edit'),   
           array('id'=>10, 
               'description'=>'Delete role','code'=>'roles_destroy'),    
           array('id'=>11, 
               'description'=>'Update role','code'=>'roles_update'),    
           array('id'=>12, 
               'description'=>'List roles','code'=>'roles_index'),     
           array('id'=>13, 
               'description'=>'Update role','code'=>'roles_permissions_edit'), 
           array('id'=>14, 
               'description'=>'Update role','code'=>'roles_permissions_update'),
           array('id'=>15, 
               'description'=>'Add shop','code'=>'shops_create'),   
           array('id'=>16, 
               'description'=>'Edit shop','code'=>'shops_edit'),   
           array('id'=>17, 
               'description'=>'Delete shop','code'=>'shops_destroy'),    
           array('id'=>18, 
               'description'=>'Update shop','code'=>'shops_update'),    
           array('id'=>19, 
               'description'=>'Update shop','code'=>'shops_store'),  
           array('id'=>20, 
               'description'=>'List shops','code'=>'shops_index'),
           array('id'=>21, 
               'description'=>'Add Descriptor','code'=>'descriptors_create'),   
           array('id'=>22, 
               'description'=>'Edit Descriptor','code'=>'descriptors_edit'),   
           array('id'=>23, 
               'description'=>'Delete Descriptor','code'=>'descriptors_destroy'),    
           array('id'=>24, 
               'description'=>'Update Descriptor','code'=>'descriptors_update'),    
           array('id'=>25, 
               'description'=>'Update Descriptor','code'=>'descriptors_store'),  
           array('id'=>26, 
               'description'=>'List Descriptors','code'=>'descriptors_index'),
           array('id'=>27, 
               'description'=>'Add Descriptor type','code'=>'descriptorsTypes_create'),   
           array('id'=>28, 
               'description'=>'Edit Descriptor type','code'=>'descriptorsTypes_edit'),   
           array('id'=>29, 
               'description'=>'Delete Descriptor type','code'=>'descriptorsTypes_destroy'),    
           array('id'=>30, 
               'description'=>'Update Descriptor type','code'=>'descriptorsTypes_update'),    
           array('id'=>31, 
               'description'=>'Update Descriptor type','code'=>'descriptorsTypes_store'),  
           array('id'=>32, 
               'description'=>'List Descriptor types','code'=>'descriptorsTypes_index'),
           array('id'=>33, 
               'description'=>'Add product','code'=>'products_create'),   
           array('id'=>34, 
               'description'=>'Edit product','code'=>'products_edit'),   
           array('id'=>35, 
               'description'=>'Delete product','code'=>'products_destroy'),    
           array('id'=>36, 
               'description'=>'Update product','code'=>'products_update'),    
           array('id'=>37, 
               'description'=>'Update product','code'=>'products_store'),  
           array('id'=>38, 
               'description'=>'List products','code'=>'products_index'),  
        ));
    }
}